### ISSUE TITLE
hCaptcha does not show up.

### ISSUE THREAD

**Issue by TheGreyRaven** [McAtze/-ITM-hCaptchaIntegration#1]
Hello, I installed your addon on a clean XenForo installation version 2.1.3 and the hCaptcha does not show.
The area where the captcha is supposed to be is just blank, I have verified both the site-key and secret-key.

**Comment by TheGreyRaven** [comment]
Small "update" on what the problem might be, it seems like the the div is not added into the registration form when looking using inspect element.
The JavaScript API is included in the header, but the div does not get added for some reason.

**Comment by ghost** [comment]
Any updates on this? Trying to implement this on my website and it simply doesn't show up.

![image](https://user-images.githubusercontent.com/16944217/79803183-2e9c7900-836a-11ea-8a8f-ef34a693b85e.png)

**Comment by McAtze** [comment]
This is addon will not be continued, take a look at this one: https://github.com/ticktackk/hCaptchaIntegrationForXF2
